env: "local"

server:
  address: "localhost:8080"
  read_timeout: "4s"
  idle_timeout: "60s"

mongo:
  hosts:
    - "0.0.0.0:27017"
  db_name: "warehouse"
  auth_source: "warehouse"
  password: "password"
  login: "warehouse"
  connect_count: 500